# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
🚀 CI / CD:
  - .github/workflows/*

📦 packages:
  - packages/**/*

🦊 mdn-webaudio-examples:
  - apps/mdn-webaudio-examples/**/*

🎵 music:
  - apps/music/**/*
