version: '3.8'

services:
  sakila:
    image: mysql:latest
    container_name: sakila
    environment:
      MYSQL_DATABASE: sakila
      MYSQL_ROOT_PASSWORD: not_a_secret_password
    restart: always
    volumes:
      - sakiladata:/var/lib/mysql
      - ./sakila-schema.sql:/docker-entrypoint-initdb.d/001-sakila-schema.sql
      - ./sakila-data.sql:/docker-entrypoint-initdb.d/002-sakila-data.sql
    ports:
      - '3306:3306'
      - '33060:33060' ## xprotocol

volumes:
  sakiladata:
    driver: local
