import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const NODE_ENV = process.env.NODE_ENV
const URL_21_DAY_CHALLENGE =
  NODE_ENV === 'development'
    ? 'http://localhost:3001/21-day-challenge'
    : '/21-day-challenge/index.html'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Evan Harmon</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href='https://nextjs.org'>Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href={URL_21_DAY_CHALLENGE} className={styles.card}>
            <h2>21 Day Challenge &rarr;</h2>
            <p>Responsive CSS Challenge</p>
          </a>
        </div>
      </main>
    </div>
  )
}

export default Home
