version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: not_a_secret_password
      MYSQL_DATABASE: my_test_db
    restart: always
    volumes:
      - db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '3306:3306'
      - '33060:33060' ## xprotocol

volumes:
  db:
    driver: local
