---
global:
  checkNewVersion: false
  sendAnonymousUsage: false

# Optional
log:
  # [TRACE, DEBUG, INFO, WARN, ERROR, FATAL]
  level: ERROR

# Optional
# Don't enable in production!!
# api:
  # dashboard: true
  # insecure: true

entryPoints:
  web:
    address: :80
    # Redirect HTTP to HTTPS
    # http:
    #   redirections:
    #     entryPoint:
    #       to: websecure
    #       scheme: https
  websecure:
    address: :443

# TODO: finish - making sure route53 is setup first and working
certificatesResolvers:
  route53:
    acme:
      storage: /var/traefik/certs/route53-acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: route53
        resolvers:
          - 
  # cloudflare:
  #   acme:
  #     email: your-email@example.com  # change this to your email
  #     storage: /var/traefik/certs/cloudflare-acme.json
  #     caServer: "https://acme-v02.api.letsencrypt.org/directory"
  #     dnsChallenge:
  #       provider: cloudflare  # Optional: change this to your DNS provider
  #       resolvers:
  #         - "1.1.1.1:53"
  #         - "8.8.8.8:53"
  
providers:
  docker:
    exposedByDefault: false # Optional: exposes all svcs when `true`
    network: frontend # should match docker-compose network
  file:
    directory: /etc/traefik
    watch: true
