# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: 'Pull Request Labeler'

on:
  pull_request_target:
    branches:
      - 'main'
    paths-ignore:
      - 'docs/**'
      - '.vscode/**'
      - '*.md'
      - 'apps/**/*.md'
      - 'packages/**/*.md'

jobs:
  label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
