import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>21 day challenge</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>21 day conquering responsive layouts </h1>

        <p className={styles.description}>
          My work going through Kevin Powell's challenges
        </p>

        <div className={styles.grid}>
          <Link href='/day01'>
            <a className={styles.card}>
              <h2>Day 1 &rarr;</h2>
            </a>
          </Link>

          <Link href='/day02'>
            <a className={styles.card}>
              <h2>Day 2 &rarr;</h2>
            </a>
          </Link>

          <Link href='/day03'>
            <a className={styles.card}>
              <h2>Day 3 &rarr;</h2>
            </a>
          </Link>

          <Link href='/day04'>
            <a className={styles.card}>
              <h2>Day 4 &rarr;</h2>
            </a>
          </Link>

          <Link href='/day05'>
            <a className={styles.card}>
              <h2>Day 5 &rarr;</h2>
            </a>
          </Link>
        </div>
      </main>
    </div>
  )
}

export default Home
